### ISSUE TITLE
Support adding graph links between different endpoints

### ISSUE THREAD

**Issue by chirino** [chirino/graphql-gw#11]
Perhaps we could do this with configuration that looks something like:

```yaml
  - name: AniCharacter
    fields:
    - name: pokemon
      select: name { full }
      vars:
        name: $..name.full
      endpoint: pokemon
      query: | 
        query($name:String) {
          pokemon(name:$name)
        }        
```

basically add a `select:` field to add addition fields to select against one upstream type that we can then use in a variable defined in `vars:` using a json path expression and then use those in the query.

**Comment by wtrocki** [comment]
Kinda confusing example as Pokemon is an object returned from this API.
So in this context we adding new field `pokemon`. 
Select is being used to include fields from **service** schema
What vars is doing in this particular context?

I like that API was just yaml and graphql queries. 
JSON path in yaml mixed with GraphQL might bring some mental barrier for people reading this snipped (but that could be just my own take here)

**Comment by chirino** [comment]
> I got the gist but, it feels that example is confusing to me as Pokemon is an object returned from this API. Is pokemon actually type?

`name: pokemon` is just a field name that is being added.  We don't specify the type.  The type for the field is whatever the upstream `query($name:String) { pokemon(name:$name) }` type is.
 
> So in this context we adding new field `pokemon`.

yep.

> Select is being used to include fields from **service** schema

Right in this case it's fields from the AniCharacter type.

> What vars is doing in this particular context?

`vars` are the variable that will be added to the upstream query.    Needed so we can do `pokemon(name:$name)` in the upstream query.

> I like that API was just yaml and graphql queries.
> JSON path in yaml mixed with GraphQL might bring some mental barrier for people reading this snippet (but that could be just my own take here)

Yeah.. seems a bit complex.  If you have ideas on how to simplify.. let me know.

**Comment by chirino** [comment]
How about this syntax instead:

```yaml
  - name: AniCharacter
    fields:
    - name: pokemon
      vars:
        $age: age                       
        $last: name { last }
        $first: name { first }
      endpoint: pokemon
      query: | 
        query {
          pokemon(age:$age, name:{first:$first, lastL$last})
        }        
```

It gets rid of the:
 1. json path stuff 
 2. `select:` fields.  
 3. declaring the variable passed into the query

**Comment by wtrocki** [comment]
This format is 500% easier to read and understand. 
I have updated it to new format to be clear that I understand it:

When having this config
  
```yaml
  - name: AniCharacter
    fields:
    - name: pokemonsWithName
      select: name { full }
      vars:
        name: $..name.full
      upstream: anilist
      query: | 
        query($name:String) {
          pokemon(name:$name)
        }        
```

With such mapping we do query form client

```graphql
query AniCharacter {
	pokemonsWithName(age:$age, first:$first, last:$last){
        ...WhateverUpstreamTypeCharacter?
    }
}
```

and the gateway is going to query anilist upstream

```graphql
query AniCharacter {
	 pokemon(age:$age, name:{first:$first, last:$last}){
        ...WhateverUpstreamTypeCharacter?
    }
}
```

**Comment by chirino** [comment]
almost right.  The client will query the gateway with something like:

```graphql
query {
  Character(id:1212) { # <-- gets me a AniCharacter
     pokemonsWithName {
        ... pokemonFields
     }
  } 
}
```

We want to use info from the anilist character to fetch data from a different upstream.. so we want to change the upstream.
```yaml
- name: AniCharacter
    fields:
    - name: pokemonsWithName
      vars:
        $age: age                       
        $last: name { last }
        $first: name { first }
      upstream: pokemons
      query: | 
        query {
          pokemon(age:$age, name:{first:$first, last:$last})
        }        
```

the gateway will first query anilist with 
```graphql
query {
  Character(id:1212) {
        _age: age                       
        _last: name { last }
        _first: name { first }  } 
}
```

and then we will query the pokemons upstream with 
```graphql
query($age:Int, $first:String, $last:String) {
  pokemon(age:$age, name:{first:$first, last:$last}) {
    ... pokemonFields
  }
}
```

**Comment by wtrocki** [comment]
Field is called `AniCharacter` but we query `Character` - how this works?

How we know about Anilist upstream? Is that because we have defined Character field in Query type in config?

`vars` could be renamed to something like `mapping` - what is really happening is that we use values from selection set as variables in another query so mapping is more descriptive

**Comment by chirino** [comment]
> Field is called `AniCharacter` but we query `Character` - how this works?

field names can be different than what they return.  When we import Schemas from upstreams, we only prefix/suffix the types, not the field names.  So in this case  the upstream field is `Character(...): Character` but when we import that into the gateway with the `Ani` prefix it's available on the gateway as `Character(...): AniCharacter`.

> How we know about Anilist upstream? Is that because we have defined Character field in Query type in config?

Your right, I should have fully specified what config we are starting with:
```yaml
upstreams:
  anilist:
    url: https://graphql.anilist.co/
    prefix: Ani
  pokemon:
    url: https://some.pokemon.service.com/
    prefix: Pokemon

types:
  - name: Query
    actions:
      - type: mount
        upstream: anilist
        query: query {}
```


> `vars` could be renamed to something like `mapping` - what is really happening is that we use values from selection set as variables in another query so mapping is more descriptive.
> 
> In the new architecture gw uses actions - maybe also new action is needed like `link`

Yeah sounds like a good idea given it assumes you can already resolve the Type your configuring so it's slightly different than a mount.
