### ISSUE TITLE
Support defining which HTTP headers to forward to the upstream.

### ISSUE THREAD

**Issue by chirino** [chirino/graphql-gw#28]
By default I think we should forward all headers to the upstreams.  But we might want to allow users be more selective about which headers to forward and also support configuring some static headers to that get sent to the upstream. 

Perhaps something like:
```yaml
upstreams:
  inventory:
    url: https://inventory-svc.myco.io/graphql
    headers:
      allow: .*
      deny: Authorization|Cookie
      set:
         API-Key: 0FAFE2123D14523F
```
